<Project>
  <PropertyGroup>
    <ApplicationIcon>../SubTubular.ico</ApplicationIcon>
    <AssemblyTitle>SubTubular - full-text search for YouTube videos</AssemblyTitle>
    <Product>SubTubular</Product>
    <VersionPrefix>4.2.0</VersionPrefix>
    <Description>Full-text-search YouTube video subtitles and metadata.</Description>
    <Authors>Holger Schmidt</Authors>
    <Copyright>Copyright © Holger Schmidt 2020-26</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>
</Project>
