<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.8.1" />
    <PackageReference Include="Lifti.Core" Version="7.0.2" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="YoutubeExplode" Version="6.6.2" />
  </ItemGroup>
</Project>